### ISSUE TITLE
formatString doesn't work

### ISSUE THREAD

**Issue by lusineartenyan** [stefalda/react-localization#47] opened 2017-09-27 21:45 UTC
Hi ,

formatString is return [object Object] instead of replacing the string in languages.

**Comment by etienne-lambert** [comment] 2018-02-02 14:41
If that can help, here's the function I used to patch the issue. I know it's far from perfect, but it might help someone.
```
const recursiveConcat = function (s: any): string {
    let ret: string = '';
    for (let a of s) {
        if (!!a) {
            if (typeof a === 'string') ret = ret.concat(a);
            else if (typeof a == 'object') ret = ret.concat(recursiveConcat(a));
        }
    }
    return ret;
}
```

**Comment by sjovanelly** [comment] 2018-08-10 21:45
I'm seeing this with IE only...works great in other browsers. Have latest react modules.

**Comment by ChezFre** [comment] 2018-09-27 08:45
Just wanted to chime in that we also had this issue. I traced it back to https://github.com/stefalda/react-localization/blob/master/src/LocalizedStrings.js#L23. `value.$$typeof` returns `number` in IE11, thus returning false and the array is joined instead of returned in `formatString`.

I don't have time to look into it right now, but we currently 'solved' it by importing `babel-polyfill` as the first line in our project.

**Comment by sivabhusarapu** [comment] 2018-11-30 11:00
I have also faced the same issue IE11, the problem is with ES6 symbols. If we add complete babel-polyfill as @ChezFre mentioned it is resolving this issue. But in my case it has added more than 150kb to my minified js file.

So, as alternative i have used 'react-app-polyfill' and imported IE11 polyfill of it 

import 'react-app-polyfill/ie11';

Now, my file size is just increased around 10kb.

**Comment by juliettech13** [comment] 2021-02-01 17:11
I thought I faced a similar issue and then realized the problem was that I was mistakenly passing an empty string to the second parameter and `formatString()` doesn't allow that... In case anyone else might be doing the same 😅

**Closed** 2021-03-18 08:52 UTC
Labels: bug, help wanted
